application: software-db
version: 1
runtime: python27
api_version: 1
threadsafe: yes



handlers:
- url: /css
  mime_type: text/css
  static_dir: css


- url: /signup
  script: main.app
  secure: always

- url: /login
  script: main.app
  secure: always

- url: /forgot
  script: main.app
  secure: always

- url: .*
  script: main.app
  secure: always


libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: "2.6"
